import Head from "next/head";

import { AnimatePresence } from "framer-motion";
import type { AppProps } from "next/app";
import Header from "../components/header/header";
import { globalStyles } from "../components/shared/styles";
import "../styles/globals.css";

interface MyAppProps extends AppProps {}
function MyApp({ Component, pageProps }: MyAppProps) {
  return (
    <>
      {globalStyles}
      <Head>
        <title>Rahul Ravindran</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <AnimatePresence
        exitBeforeEnter
        initial={false}
        onExitComplete={() => window.scrollTo(0, 0)}
      >
        <Component {...pageProps} />
      </AnimatePresence>
    </>
  );
}

export default MyApp;
