import Head from "next/head";

import { CacheProvider, EmotionCache } from "@emotion/react";
import { AnimatePresence } from "framer-motion";
import type { AppProps } from "next/app";
import Header from "../components/header/header";
import { globalStyles } from "../components/shared/styles";
import "../styles/globals.css";
import createEmotionCache from "../theme/emotion-cache";

// Client-side cache shared for the whole session
// of the user in the browser.

const clientSideEmotionCache = createEmotionCache();

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
}
function MyApp({
  Component,
  pageProps,
  emotionCache = clientSideEmotionCache,
}: MyAppProps) {
  return (
    <>
      {globalStyles}
      <CacheProvider value={emotionCache}>
        <Head>
          <title>Rahul Ravindran</title>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <AnimatePresence
          exitBeforeEnter
          initial={false}
          onExitComplete={() => window.scrollTo(0, 0)}
        >
          <Component {...pageProps} />
        </AnimatePresence>
        {/* <Footer /> */}
      </CacheProvider>
    </>
  );
}

export default MyApp;
